### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by teddybear082** [lightsoutgames/godot-tts#14]
I used this repo to create a NPC speech mod for Cruelty Squad.  Appreciate your work on this.  Not really much out there I could find and especially not as easy to implement.

**Comment by teddybear082** [comment]
I also now used this addon in this project for AI NPCs:

https://github.com/teddybear082/godot-ai-npc-example

**Comment by ndarilek** [comment]
You're welcome.

I've merged in both open PRs and will try cutting a new major release later today, but I'm likely no longer updating this plugin. Aside from a technical issue that makes Linux compatibility more difficult, Godot was too difficult to use as a blind developer and I just can't maintain a long tail of projects in maintenance mode.

If anyone wants to take over ownership then let's talk, otherwise this is likely the last release.

**Comment by ndarilek** [comment]
Actually, if anyone wants to fix all the CI errors that just popped up, that'd be great. I don't have the bandwidth to battle GitHub CI's accessibility issues today. Thanks.

**Comment by rsubtil** [comment]
Godot added native TTS support in the engine, so eventually this addon won't be necessary. Right now from my experience it's still buggy and cannot interface with some third-party software (e.g. NVDA on Windows), so this addon is still better.

> Actually, if anyone wants to fix all the CI errors that just popped up, that'd be great. I don't have the bandwidth to battle GitHub CI's accessibility issues today. Thanks.

I took a peek to see what might be going on. Regarding the "Check" failing, seems like a random error cargo decided to throw that time. I tried running the CI on my fork and the check passed without issue, so you might need to just run the CI again.

As for the Android build, seems like that behavior was deprecated, and removed from [version 7 onwards](https://docs.gradle.org/6.8/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed), hence the error now popping up. I don't have experience developing on Android, so I hope someone else can fix it.

Lastly, I really want to thank you for your work. I have a user that is fully blind and wanted to use a project I'm developing. This addon and the `godot-accessibility` addon work really well, and integrating them was effortless.
